CREATE DATABASE TEST;
CREATE TABLE CUSTOMERS(ID ,FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONENUMBER VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)

)
GO 

CREATE TABLE ORDERS (ORDERNO INT NOT NULL,
ORDERDATE DATE NOT NULL,
CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMERS(ID),
PRICE INT)





GO 
CREATE TABLE PRODUCTS(PRODUCTID INT,EXPIREDAT DATE NOT NULL,
PRODUCTNAME VARCHAR(15) NOT NULL,
PRODUCTPRICE INT NOT NULL,
CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMERS(ID),

PRIMARY KEY(PRODUCTID)

)
GO 

CREATE TABLE EMPLOYEE(EMPLOYEENAME VARCHAR(30) NOT NULL,
EMPLSALARY INT NOT NULL,
EMPLOYEEPHONE VARCHAR(10) NOT NULL,
EMPLEMAIL VARCHAR(50) NOT NULL 
PRIMARY KEY (EMPLOYEENAME))
INSERT INTO PRODUCTS VALUES(3,'2028-12-14','BOX',1000,5)

INSERT INTO ORDERS VALUES(5,'2022-12-14',3,17,'MAQLOUBEH')

SELECT * FROM PRODUCTS
ALTER TABLE ORDERS ADD ORDERETYPE varchar(100) ;


SELECT * FROM ORDERS
SELECT * FROM CUSTOMERS

--ORDERS WITH CUSTOMERS 
SELECT * FROM CUSTOMERS AS C  INNER JOIN ORDERS AS O 
ON O.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  LEFT JOIN ORDERS AS O 
ON O.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  RIGHT JOIN ORDERS AS O 
ON O.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  FULL JOIN ORDERS AS O 
ON O.CUSTOMERID=C.ID

--OPRODUCTS WITH CUSTOMERS 
SELECT * FROM CUSTOMERS AS C  INNER JOIN PRODUCTS AS P
ON P.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  LEFT JOIN PRODUCTS AS P
ON P.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  RIGHT JOIN PRODUCTS AS P
ON P.CUSTOMERID=C.ID

SELECT * FROM CUSTOMERS AS C  FULL JOIN PRODUCTS AS P
ON P.CUSTOMERID=C.ID









